[site]
title = "Liping Zhao"
description = "PhD student at the University of Hong Kong."
favicon = "/favicon.svg"
last_updated = "March 26, 2026"

[author]
name = "Liping Zhao"
title = "PhD Student"
institution = "the University of Hong Kong"
avatar = "/LipingZhao/me.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "lzhao3976@gmail.com"
orcid = "https://orcid.org/0009-0001-4425-4139"


[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"


[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
