type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."

[[items]]
title = "Practice Research in Human Services"
subtitle = "Teaching Assistant"
date = "2025"
content = ""
tags = ["Graduate"]

[[items]]
title = "Human Behaviour and the Social Environment II"
subtitle = "Teaching Assistant"
date = "2025"
content = ""
tags = ["Graduate"]

[[items]]
title = "Social Policy and Administration"
subtitle = "Teaching Assistant"
date = "2025"
content = ""
tags = ["Graduate"]

[[items]]
title = "Social Development: China, Asia, and the World (Common Core Course)"
subtitle = "Teaching Assistant"
date = "2023"
content = ""
tags = ["Undergraduate"]

[[items]]
title = "Social Research Methods"
subtitle = "Teaching Assistant"
date = "2023"
content = ""
tags = ["Graduate"]
